import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "@/assets/fonts";
import Navbar from "./sidenav/page";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
